name: Build app
permissions:
  contents: read
on:
 - workflow_dispatch
  	
jobs:
  build_for_linux:
    runs-on: [tonymushah-fedora-latest]
    container:
      image: ubuntu:24.04
    env:
       FORGEJO_TOKEN: ${{ secrets.BUILD_APP_TOKEN }}
       REPO_OWNER: ${{ forgejo.repository_owner }}
       CURRENT_REPO: ${{ forgejo.repository }}
    steps:
      - name: Checkout the repository
        uses: https://data.forgejo.org/actions/checkout@v6
      - name: install dependencies
        run: |
          sudo apt update;
          sudo apt install -y \
            build-essential \
            procps \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            xdg-utils \
            librsvg2-dev \
            dasel \
            nsis \ 
            tar \
            zip;
          sudo apt install -y \
            libwebkit2gtk-4.1-0=2.44.0-2 \
            libwebkit2gtk-4.1-dev=2.44.0-2 \
            libjavascriptcoregtk-4.1-0=2.44.0-2 \
            libjavascriptcoregtk-4.1-dev=2.44.0-2 \
            gir1.2-javascriptcoregtk-4.1=2.44.0-2 \
            gir1.2-webkit2-4.1=2.44.0-2;
      - name: install rust
        run: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
      - name: install just 
        run: |
            cargo install --locked just
      - name: install pnpm 
        run: |
            wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -
      - name: install vite plus       
        name: |
            curl -fsSL https://vite.plus | bash
      - name: install app deps
        run: |
            just setup
      - name: download llvm-mingw
        run: |
            just download-gnu-llvm
      - name: build app
        run: |
            APP_VERSION=$(cat Cargo.toml | dasel -i toml workspace.package.version) just slow-build-release
      - name: install forgejo cli
        run: |
            cargo install --locked forgejo-cli
      - name: setup forgejo auth
        run: |
            fj auth add-key "$(echo $FORGEJO_OWNER)" $(echo $FORGEJO_TOKEN)
      - name: Send the release assets x86_64 to the current release
        run: |
            set -x
            EUREKA_VERSION=$(cat Cargo.toml | dasel -i toml workspace.package.version)
            fj release create -B main -d -T $(echo $EUREKA_VERSION) $(echo $EUREKA_VERSION)
            find target/release-bundles -maxdepth 1 -type f -exec fj release asset create $(echo $EUREKA_VERSION) "{}" \;